### ISSUE TITLE
fill-in image properties when publishing an instance

### ISSUE THREAD

**Issue by melato** [melato/lxops#24]
The incus publish command allows setting image properties: description, name, os, release, serial, variant, which go into the image metadata.yaml file.

An example from an images:alpine/3.19 image:
```
properties:
  architecture: aarch64
  description: Alpinelinux 3.19 aarch64 (20240426_13:00)
  name: alpinelinux-3.19-aarch64-default-20240426_13:00
  os: alpinelinux
  release: "3.19"
  serial: "20240426_13:00"
  variant: default
```

When I use "incus publish" to create an image from an instance.  I typically set only the alias (which is not in metadata.yaml).
This causes the new image to have the same properties as the image that the instance was created from.  This was not a problem while I used images by alias.  But I recently tried to make a simplestreams image server from my images, and they were listed with misleading metadata.

Modify "lxops instance publish" so that it can set the image properties.  The "name" and "description" properties seem to have a certain structure that incorporates other properties (release, architecture, serial, variant).  Generate "name" and "description" automatically.
From the above properties, only "alpinelinux" needs to be specified, and it can default to the "os" of the original image.
