### ISSUE TITLE
allow devices without filesystem

### ISSUE THREAD

**Issue by melato** [melato/lxops#3]
Proposal: The lxops (config) file could have a way to attach a device without creating a filesystem for it.
That will provide a quick way of specifying a disk device to a container, by putting it directly in the config file.
I often attach devices to share directories between containers, or between the host and containers.  I've been doing this via profiles, so I have a lot of small profiles which are sometimes used by only one container.

We can use the existing "devices" syntax without the filesystem field:

```
devices:
   dev1:
     path: /<path-in-container>
     dir: /<path-in-host>
```

If the filesystem is empty, dir should be absolute.
